### PR TITLE
1st pull request for SceneVR

### PR DESCRIPTION
**Pull request by qster123**

### CODE REVIEW

**Comment by bnolan** [comment]
Emailed you some notes, basically:

The sun angle has changed so there isnt the hard core light rays.
Should use orange light #ff7700 in a few of the rooms because thats the scene vr clor.
This lightmap looks way better baked than the currnet one. :+1:

**Comment by qster123** [comment]
Time for me to crash, I'll carry on this week! All understood!

Let me know the size/font/colours used in your logo please (or send me the source imagery).

--------- Original Message --------- Subject: Re: [home] 1st pull request for SceneVR (#2)

**Comment by qster123** [comment]
Morning!

Could you let me know the font size/type for your logo?

doing morning chores then I'll get cracking on the model

--------- Original Message --------- Subject: Re: [home] 1st pull request for SceneVR (#2)

**Comment by bnolan** [comment]
Helvetica Neue bold! I don't have a specific font size :)

On Tuesday, March 17, 2015, Lee Nolan notifications@github.com wrote:

> Morning!
> 
> Could you let me know the font size/type for your logo?
> 
> doing morning chores then I'll get cracking on the model
> 
> --------- Original Message --------- Subject: Re: [home] 1st pull request
> for SceneVR (#2)
> From: "Ben Nolan" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> Date: 3/15/15 3:24 pm
> To: "scenevr/home" <home@noreply.github.com
> <javascript:_e(%7B%7D,'cvml','home@noreply.github.com');>>
> Cc: "Lee Nolan" <hello@vrsites.com
> <javascript:_e(%7B%7D,'cvml','hello@vrsites.com');>>
> 
> Emailed you some notes, basically:
> The sun angle has changed so there isnt the hard core light rays.
> Should use orange light #ff7700 in a few of the rooms because thats the
> scene vr clor.
> 
> ## This lightmap looks way better baked than the currnet one.
> 
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/scenevr/home/pull/2#issuecomment-81584718.

## 

Regards,
Ben Nolan

http://bennolan.com/

skype: bennolan
cell: +64 21 770 662

**Comment by bnolan** [comment]
Heya, I merged the PR manually. 

Try updating your fork from this one, and do another PR and we'll see how we go! I converted the lightmaps to jpeg quality 90, let me know if you disagree with this, I think it looks ok and is 30% the size. :+1: 

Thank you! :)

**Comment by bnolan** [comment]
One thing - can you send me the .blend file as a pull request, so we're all working off the same content? How did you retriangulate it so well?

**Comment by qster123** [comment]
Hey,

It should have been included? qster_homeroom.blend in the blends directory
should have been uploaded somewhere!

[image: http://vrsites.com] http://vrsites.com
https://www.facebook.com/vrsites http://twitter.com/vrsites/
http://www.reddit.com/r/vrsites https://plus.google.com/+Vrsites
https://github.com/vrsites

**Pull request closed without merging**
